### PR TITLE
Jae hun jung it4

### PR DESCRIPTION
**Pull request by JaeHun0304**
Hello, all
I disabled the encryption feature on the course/section ID column.
The excel download feature will be working fine after merge this request.
Try manually change the code based on this request if want to test the excel download feature is working correctly.

### CODE REVIEW

**Comment by rupimanoj** [comment]
> Hello, all
> I disabled the encryption feature on the course/section ID column.
> The excel download feature will be working fine after merge this request.
> Try manually change the code based on this request if want to test the excel download feature is working correctly.

**Comment by rupimanoj** [comment]
Cant, we keep encrypted data as it is in the database and decrypt only during excel sheet creation.

**Comment by JaeHun0304** [comment]
Okay. But unfortunately, I tried to use decrypt API by instruction from the attr_encrypt gem. It is not working and I doubt to complete it on deadline.

**Comment by rupimanoj** [comment]
In the second commit, why files are deleted? You should revert first commit changes, buy why deletion?

**Pull request closed without merging**
